language: node_js
dist: trusty
sudo: false
node_js:
  - '6'
  - '7'
  - '8'
deploy:
  provider: npm
  email: vossad01@gmail.com
  api_key:
    secure: >-
      sNO19+NGAmQncPhRP9LA59Q7TnvBmJ+aHxaNXaLFUnwVy1O4HWOeH4B0cqaaNOOpuknAEhtuU1p5E9XpehHHgW18XdTdiHuE81uOFQP1CDgEC8EKidOM85CsTlEyN8J9bF+dVwoCnyttPjk0Gg3Ohm9A6apBvn6TDJSAehM7Z03M2Py65o4svvViBA8q2tV5P1Jyl6NT7E/1YRWpYV+GnB2zpWsodk3Vu/ZoMFFjKVjxsl+Z5OxfkVb/+AW6fxSHRJjN7/qFy8ycQfz2gU/iMNxF6nD5tsQWHQf8uRTrRWkDrDpFiU6LC67QwA2eVRoS/DZYTSvUi+0Y45ZD8lomNsXq3FekpbcKv8OGcv+G2UKGO3C57wd9keqqFyEFYHfBAoiO292yjGkWqo0I4E8cFYnKE8Wz/NLGW4uRAcOMyi6vfCWhNaQgUsS4xMNjgsrlapXjtw94ql+fIqQX8MKmT2R3gpt0BbMK2y4czE0gjAtMUbkZc7JEpzCR7JPkXHrKCCM56QJgHpaEbgFQTTZOkyEfxAFUyM6JxJ/wyN1u3s+TDhEQH4aIykCTcd3LeJcBQF5AMRUqRBxa+tpV+P9YYww4UayTQdSJjWzmO9DRaNTeanv0B0xJUOKjNk6V7xKUPixKcwlSDGr2Ve7UW2CQhw+gqKrWTT2s+DaxfWm4+BY=
  on:
    tags: true
    repo: adamvoss/vscode-yaml-languageservice
